//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOES_BUSINESS_IN
    {
        public Nullable<int> Territory_ID { get; set; }
        public Nullable<int> Customer_ID { get; set; }
        public int DOES_BUSINESS_ID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual SALES_TERRITORY SALES_TERRITORY { get; set; }
    }
}
