//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALES_PERSON
    {
        public int Salesperson_ID { get; set; }
        public string Salesperson_Name { get; set; }
        public string Salesperson_Telephone { get; set; }
        public string Salesperson_Fax { get; set; }
        public Nullable<int> Territory_ID { get; set; }
    
        public virtual SALES_TERRITORY SALES_TERRITORY { get; set; }
    }
}
