//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USES
    {
        public Nullable<int> Material_ID { get; set; }
        public Nullable<int> Product_ID { get; set; }
        public int USES_ID { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual RAW_MATERIAL RAW_MATERIAL { get; set; }
    }
}
