//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORKS_IN
    {
        public Nullable<int> Employee_ID { get; set; }
        public Nullable<int> Work_Center_ID { get; set; }
        public int WORKS_IN_ID { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual WORK_CENTER WORK_CENTER { get; set; }
    }
}
